### PR TITLE
#167188025 Build out user view all blogs webpage

### PR DESCRIPTION
**Pull request by nshutijonathan**
#### What does this PR do?
Have a User view all blogs  page Working
#### Description of Task to be completed?
Have This UI page working
* AndaApp/UI/templates/blogs.html
#### How should this be manually tested?
* After cloning the repo,  checkout into ft-user-view-all-blogs-167188025 branch then cd into AndaApp then  open blogs.html in the browser 
#### Any background context you want to provide?
* There is Implementation of CSS, and Html
#### What are the relevant pivotal tracker stories?
[#167188025](https://www.pivotaltracker.com/n/projects/2367349/stories/167188025)
—
#### Screenshots
image

### CODE REVIEW

**Comment by Anguandia** [comment]
Good work Jonathan! It would be great to consider a few of these:
  - The design on figma has an avatar in the right of the header, reconciling this with the built page would be good
  - Just before the listing of posts, the figma design has a summary of number of posts found, a 'show this week' link and a 'status' bar (green). My personal thought is that the bar's relevance and scale need to be discussed
  - Please check the relative width of the blogs to the window from the figma design, there looks to be some bit of disparity with design
  - The avatars for the individual posts listed
  - I like the footer, it would be good if we adopted it for the entire site, please implore the team to.
Good work, address the salient and merge

**Review by salviosage — COMMENTED** [review]
nice work so far, can you align a read more button right and try to add avatar pic for a writer?

**Review by Anguandia — APPROVED** [review]

**Review by minega25 — CHANGES_REQUESTED** [review]
- Would you kindly use the roboto font
- align readme button on the right side of the box (you can use float: right)

**Review by habinezadalvan — CHANGES_REQUESTED** [review]
You are on the way, you would please follow the mockup and position icons and avatar picture in their right place.

**Pull request merged**
