### PR TITLE
#167187997 User should be able to create a blog post

### PR DESCRIPTION
**Pull request by minega25**
#### What does this PR do?

- Add user can create a blog post user interface

#### Description of Task to be completed?

- Add summernote wysiwyg editor
- Add dashboard sidebar
#### How should this be manually tested?

1. Create a feature branch with name ft-user-create-blog-167187997 and checkout into it from gh-pages branch.
2. Enter `git pull origin ft-user-create-blog-167187997`

#### What are the relevant pivotal tracker stories?

- [#167187997](https://www.pivotaltracker.com/story/show/167187997) 

#### Screenshots
Screen Shot 2019-07-17 at 05 47 55

#### Questions:

### CODE REVIEW

**Review by Anguandia — APPROVED** [review]
Good work there! Design well translated into actual page, just a few suggestions to cross the t's
  - I think it would be good to remove eliminate redundancy of the avatar on the same page (from the design on Figma, say, decide to keep one of dashboard or header)
  - Reconcile the area icon on the figma design with its absence in the page implementation if possible
  - Just a reminder to include the settings link in the dashboard of the built page
  - I think eliminating the search and compose blog post link in the main window above the editor was a great idea, it would be good to do so in the design on figma too.
  - What do you think about making the editor window (text area) height auto increase to accommodate content? Just thinking...
  - It would be an extra to add some visual effect for the click action of the publish button

Nice work, consider these suggestions and merge

**Review by salviosage — APPROVED** [review]
nice work

**Review by nshutijonathan — APPROVED** [review]
nice work so far

**Review by habinezadalvan — APPROVED** [review]
Nice work patrick;

**Review by nkalyesubula — APPROVED** [review]
Nice work

**Pull request merged**
