### PR TITLE
#167187978 UI login page

### PR DESCRIPTION
**Pull request by habinezadalvan**
**What does this PR do?**

- Creates login pages.

**Description of Task to be completed?**

- Completed a login UI page where the user will be able to fill his/her credentials to login to anda app or use google or facebook credentials.

**How should this be manually tested?**

- After cloning the repo, git checkout ft-ui-login-167187978, open login.hrml file in any browser.

**What are the relevant pivotal tracker stories?**
[#167188025](https://www.pivotaltracker.com/story/show/167187988)
@nshutijonathan @minega25 @Anguandia @salviosage @nkalyesubula 
Screen Shot 2019-07-17 at 14 04 35

### CODE REVIEW

**Review by salviosage — APPROVED** [review]
nice work so far.

**Review by minega25 — APPROVED** [review]
This good work.

**Comment by nkalyesubula** [comment]
The pivotal tracker ID should be a clickable link

**Review by nshutijonathan — APPROVED** [review]
Good job

**Review by nkalyesubula — APPROVED** [review]

**Pull request merged**
