### PR TITLE
#167189379 Set up a system folder structure

### PR DESCRIPTION
**Pull request by nkalyesubula**
#### What does this PR do?
Set up a system folder structure
#### Description of Task to be completed?
This is intended to include all necessary folders and files needed to get started with building the app
#### What are the relevant pivotal tracker stories?
[#167189379](https://www.pivotaltracker.com/story/show/167189379)
@habinezadalvan @minega25 @nshutijonathan @salviosage

### CODE REVIEW

**Comment by nshutijonathan** [comment]
The set-up is fine You can go ahead so that we can get started with implementing our features

**Review by minega25 — APPROVED** [review]
This is fine with me you can go ahead and merge

**Comment by salviosage** [comment]
it's okay you can merge

**Review by nshutijonathan — APPROVED** [review]

**Review by habinezadalvan — COMMENTED** [review]
I think the index.html file has to be immediately under the UI folder to be easily displayed when gh-pages link runs.

**Comment by Anguandia** [comment]
- Would be good to have the index file at the root but we still can work around with it in the templates folder
- You can merge

**Review by salviosage — COMMENTED** [review]
this is cool you can merge

**Review by salviosage — APPROVED** [review]

**Review by habinezadalvan — APPROVED** [review]

**Comment by nkalyesubula** [comment]
> it's okay you can merge



> I think the index.html file has to be immediately under the UI folder to be easily displayed when gh-pages link runs.

This is the standard we agreed upon as a team. please reach out to any of the team members for more clarifications.

**Pull request merged**
